# Copyright (c) 2026 Nakata Maho
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

"""Generate ALTPRB.COM: the alternate register set across a CALLN round trip.

The uPD9002's AF'/BC'/DE'/HL' are register storage that native mode cannot
address (upd9002-upd70008-mode.md 3.1).  ALTPRB loads known patterns into
the alternate set and the main set, performs CALLN 91h (the firmware's V3
memory-read service, 7.1: A = 00h byte read, HL = segment, DE = offset,
BC <- value), and records every register right after the return.  The
read targets the VA2 boot ROM byte at F000h:13EDh (33h, the first byte of
the vector installer, 4.7.3), so a correct result also proves the round
trip happened.  Case X0 is a control without CALLN.

Each case writes two 128-byte records, closed as checkpoints:

    Xn I AF=.... BC=.... DE=.... HL=.... IX=.... IY=.... SP=.... AF'=.... BC'=.... DE'=.... HL'=....
    Xn O AF=.... BC=.... DE=.... HL=.... IX=.... IY=.... SP=.... AF'=.... BC'=.... DE'=.... HL'=....

Real machine only: the CP/M host runner cannot execute CALLN.  z80asm 1.8
syntax; cpmio.asm is appended by zexbuild.py.
"""

from __future__ import annotations

RECORD = 128
# (calln, af_in): A = 00h selects "memory read, byte"; F differs per case.
CASES = [(False, 0x00D7), (True, 0x00D7), (True, 0x0000), (True, 0x00C5)]
ALT = {"af": 0xAA45, "bc": 0xA1A2, "de": 0xB1B2, "hl": 0xC1C2}
MAIN = {"bc": 0x0000, "de": 0x13ED, "hl": 0xF000, "ix": 0x1111, "iy": 0x2222}


def case_block(index: int, calln: bool, af_in: int, last: bool) -> str:
    goto = "run_end" if last else f"q_{index + 1:02x}"
    calln_bytes = "\tdb\t0edh,0edh,091h\t; CALLN 91h\n" if calln else ""
    return f"""
q_{index:02x}:	ld	a,'X'
	call	putc
	ld	a,{index}
	call	hexdig
	ld	de,s_in
	call	puts
	ld	hl,0{af_in:04x}h
	ld	(iaf),hl
	call	report_in
	ld	a,'X'
	call	putc
	ld	a,{index}
	call	hexdig
	ld	de,s_out
	call	puts
	di
	exx
	ld	bc,0{ALT['bc']:04x}h
	ld	de,0{ALT['de']:04x}h
	ld	hl,0{ALT['hl']:04x}h
	exx
	ld	bc,0{ALT['af']:04x}h
	push	bc
	pop	af
	ex	af,af'
	ld	ix,0{MAIN['ix']:04x}h
	ld	iy,0{MAIN['iy']:04x}h
	ld	bc,0{af_in:04x}h
	push	bc
	pop	af
	ld	bc,0{MAIN['bc']:04x}h
	ld	de,0{MAIN['de']:04x}h
	ld	hl,0{MAIN['hl']:04x}h
{calln_bytes}	push	af
	push	bc
	push	de
	push	hl
	push	ix
	push	iy
	exx
	push	bc
	push	de
	push	hl
	exx
	ex	af,af'
	push	af
	ex	af,af'
	ld	(osp),sp
	ei
	pop	hl
	ld	(oaf2),hl
	pop	hl
	ld	(ohl2),hl
	pop	hl
	ld	(ode2),hl
	pop	hl
	ld	(obc2),hl
	pop	iy
	ld	(oiy),iy
	pop	ix
	ld	(oix),ix
	pop	hl
	ld	(ohl),hl
	pop	hl
	ld	(ode),hl
	pop	hl
	ld	(obc),hl
	pop	hl
	ld	(oaf),hl
	ld	hl,(osp)
	ld	de,20
	add	hl,de
	ld	(osp),hl		; SP as it was after the CALLN
	call	report_out
	jp	{goto}
"""


def source() -> str:
    blocks = "".join(case_block(i, c, f, i == len(CASES) - 1) for i, (c, f) in enumerate(CASES))
    return f"""; M103a ALTPRB: generated by tools/cpmva/zex/altprb.py; do not edit.
;
; Alternate register set across a CALLN 91h round trip; see altprb.py.
; Writes ALTPRB.TXT in {RECORD}-byte records, closed after every record.

	org	100h

start:	ld	sp,stack
	ld	de,fcbout
	call	fopen
	ld	de,title
	call	conmsg
	ld	hl,0
	add	hl,sp
	ld	(isp),hl
	jp	q_00

; print the input line from the constants and (iaf)/(isp)
report_in:
	ld	hl,(iaf)
	call	field
	ld	hl,0{MAIN['bc']:04x}h
	call	field
	ld	hl,0{MAIN['de']:04x}h
	call	field
	ld	hl,0{MAIN['hl']:04x}h
	call	field
	ld	hl,0{MAIN['ix']:04x}h
	call	field
	ld	hl,0{MAIN['iy']:04x}h
	call	field
	ld	hl,(isp)
	call	field
	ld	hl,0{ALT['af']:04x}h
	call	field
	ld	hl,0{ALT['bc']:04x}h
	call	field
	ld	hl,0{ALT['de']:04x}h
	call	field
	ld	hl,0{ALT['hl']:04x}h
	call	field
	call	recend
	ret

report_out:
	ld	hl,(oaf)
	call	field
	ld	hl,(obc)
	call	field
	ld	hl,(ode)
	call	field
	ld	hl,(ohl)
	call	field
	ld	hl,(oix)
	call	field
	ld	hl,(oiy)
	call	field
	ld	hl,(osp)
	call	field
	ld	hl,(oaf2)
	call	field
	ld	hl,(obc2)
	call	field
	ld	hl,(ode2)
	call	field
	ld	hl,(ohl2)
	call	field
	call	recend
	ret

; write ' ' + hl as four hex digits (field names are in s_in/s_out order)
field:	push	af
	push	de
	ld	a,(fidx)
	ld	e,a
	ld	d,0
	push	hl
	ld	hl,ftab
	add	hl,de
	add	hl,de
	ld	e,(hl)
	inc	hl
	ld	d,(hl)
	call	puts
	pop	hl
	call	hex4
	ld	a,(fidx)
	inc	a
	cp	11
	jp	nz,fnext
	ld	a,0
fnext:	ld	(fidx),a
	pop	de
	pop	af
	ret

; pad the record with spaces, end it with CR LF, close as a checkpoint
recend:	push	af
	push	bc
	push	de
	push	hl
rpad:	ld	a,(fcnt)
	cp	2
	jp	z,rcr
	ld	a,' '
	call	fputc
	jp	rpad
rcr:	ld	a,13
	call	putc
	ld	a,10
	call	putc
	ld	de,(curfcb)
	ld	c,16
	call	bdosv
	pop	hl
	pop	de
	pop	bc
	pop	af
	ret

run_end: call	fclose
	ld	de,done
	call	conmsg
	jp	0

title:	db	'# ALTPRB M103a alternate registers across CALLN 91h',13,10,'$'
done:	db	'ALTPRB done',13,10,'$'
s_in:	db	' I$'
s_out:	db	' O$'
ftab:	dw	f_af,f_bc,f_de,f_hl,f_ix,f_iy,f_sp,f_af2,f_bc2,f_de2,f_hl2
f_af:	db	' AF=$'
f_bc:	db	' BC=$'
f_de:	db	' DE=$'
f_hl:	db	' HL=$'
f_ix:	db	' IX=$'
f_iy:	db	' IY=$'
f_sp:	db	' SP=$'
f_af2:	db	' AF',27h,'=$'
f_bc2:	db	' BC',27h,'=$'
f_de2:	db	' DE',27h,'=$'
f_hl2:	db	' HL',27h,'=$'
fidx:	db	0
iaf:	dw	0
isp:	dw	0
oaf:	dw	0
obc:	dw	0
ode:	dw	0
ohl:	dw	0
oix:	dw	0
oiy:	dw	0
osp:	dw	0
oaf2:	dw	0
obc2:	dw	0
ode2:	dw	0
ohl2:	dw	0
fcbout:	db	0,'ALTPRB  TXT'
	db	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	ds	128
stack:
{blocks}"""
