# Copyright (c) 2026 Nakata Maho
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.

"""Generate the M102 EDPRB2 probe source (z80asm 1.8).

EDPRB2 is the second one-by-one probe of the undefined ED opcodes. Compared
with EDPRB it keeps every register pointer inside a recorded sandbox, detects
the instruction length with an RST 08h sled, runs three input sets per
opcode, and skips the opcodes that left the emulation mode on the real
machine unless asked to run them. EDPRB2S is the same probe for a few
opcodes with the code moved by SHIFT bytes, to test whether a result depends
on the program layout.
"""

from __future__ import annotations

# Probe order and classes. Class 1: documented controls (run only from 00).
# Class 2: opcodes that left the CP/M emulation mode on the real PC-88VA2 in
# EDPRB run 3 (54, 55, AC, EE-FC); they run only with '+' in the tail.
CONTROLS = (0x44, 0x45)
EXITS_EMULATION = frozenset([0x54, 0x55, 0xAC] + list(range(0xEE, 0xFD)))
PROBED = tuple(
    list(range(0x00, 0x40))
    + [0x4C, 0x54, 0x55, 0x5C, 0x5D, 0x64, 0x65, 0x6C, 0x6D, 0x74, 0x75, 0x77, 0x7C, 0x7D, 0x7F]
    + list(range(0x80, 0xA0))
    + [0xA4, 0xA5, 0xA6, 0xA7, 0xAC, 0xAD, 0xAE, 0xAF, 0xB4, 0xB5, 0xB6, 0xB7,
       0xBC, 0xBD, 0xBE, 0xBF]
    + [op for op in range(0xC0, 0x100) if op not in (0xED, 0xFD)]
)
SHIFTED_PROBES = (0x00, 0x10, 0x20, 0x30, 0x64, 0x6C, 0x74, 0x80, 0xA4)
SHIFT = 0x100
SETS = 3
SLED = 6
# The register image of each set: AF and BC. BC stays a small count that
# points into the scratch page 0100h-01FFh.
SET_AF = (0x5AD7, 0xA500, 0x3CC5)
SET_BC = (0x0130, 0x0150, 0x0180)
BUFFERS = ("B", "D", "H", "X", "Y", "S")
# Fixed sandbox addresses outside the program image, 800h apart; the
# recorded window of each is pointer-4 .. pointer+3.
ADDRESSES = {
    "bufd": 0x3404, "bufh": 0x3C04, "bufx": 0x4404, "bufy": 0x4C04,
    "tstk": 0x5404, "capstk": 0x5C00, "stack": 0x6000, "obuf": 0xCFCF,
}
CODE_LIMIT = 0x2000  # the image must end below the 2000h-2FFFh guard range

RECORD = 256


def variants() -> dict[str, dict]:
    return {
        "EDPRB2": {"prefix": "E2", "shift": 0, "probes": PROBED, "controls": CONTROLS},
        "EDPRB2S": {"prefix": "S2", "shift": SHIFT, "probes": SHIFTED_PROBES, "controls": ()},
    }


def pattern(set_index: int, buffer_index: int) -> list[int]:
    """Eight distinct bytes for one buffer of one set."""
    if set_index == 0:
        values = [((buffer_index + 1) << 4) | i for i in range(8)]
    elif set_index == 1:
        values = [((buffer_index + 8) << 4) | (8 + i) for i in range(8)]
    else:
        values = [(((buffer_index + 1) << 4) | i) ^ 0xFF for i in range(8)]
    return values


def probe_class(op: int, controls: tuple[int, ...]) -> int:
    if op in controls:
        return 1
    return 2 if op in EXITS_EMULATION else 0


def body(op: int, cls: int, tag: str) -> str:
    sled = ",".join(["0cfh"] * SLED)
    return f"""
; ---- ED {op:02X}
p_{tag}:	ld	a,0{op:02x}h
	ld	b,{cls}
	ld	hl,k_{tag}
	call	begin		; returns only when this probe runs
	ld	(mainsp),sp
	ld	sp,tstk
	db	0edh,0{op:02x}h	; under test
	db	{sled}	; RST 08h sled
	jp	fall
k_{tag}:
"""


def db(values: list[int]) -> str:
    return "\tdb\t" + ",".join(f"0{v:02x}h" for v in values) + "\n"


def source(name: str) -> str:
    variant = variants()[name]
    prefix = variant["prefix"]
    lines = [f"""; M102 {name}: generated by tools/cpmva/zex/edprb2.py; do not edit.
;
; usage: {name} [start][+]   start = hex opcode (default 00); '+' also runs the
; opcodes that left the CP/M emulation mode in EDPRB run 3. The output file
; is {prefix}xx.TXT, xx = start. Every opcode runs once per input set (0-{SETS - 1}),
; and each result is one {RECORD}-byte record; the file is closed after each.

	org	100h
	jp	start
scratch: ds	0fdh		; 0103h-01FFh: BC points here
"""]
    if variant["shift"]:
        lines.append(f"\tds\t0{variant['shift']:x}h\t\t; layout shift\n")
    lines.append("""start:	ld	sp,stack
	call	parse
	ld	hl,8		; save the RST 08h vector
	ld	de,oldrst
	ld	bc,3
	ldir
	ld	de,title
	call	conmsg
	ld	de,fcbout
	call	fopen
	xor	a
	ld	(curset),a
""")
    for op in variant["controls"]:
        lines.append(body(op, 1, f"c{op:02x}"))
    for op in variant["probes"]:
        lines.append(body(op, probe_class(op, variant["controls"]), f"{op:02x}"))
    lines.append(f"""
	ld	hl,oldrst	; restore the RST 08h vector
	ld	de,8
	ld	bc,3
	ldir
	call	fclose
	jp	0

; begin a probe: a = opcode, b = class, hl = the next probe. Skip it, or
; prepare the sandbox, load the registers of the current set under DI and
; return to the probe body.
begin:	ld	(curop),a
	ld	(nexta),hl
	pop	hl
	ld	(cont),hl
	ld	a,b
	dec	a
	jp	z,bctl		; 1: control
	dec	a
	jp	nz,bord		; 0: ordinary
	ld	a,(allflg)	; 2: only with '+'
	or	a
	jp	z,bskip
bord:	ld	a,(curop)
	ld	hl,startop
	cp	(hl)
	jp	c,bskip
	jp	brun
bctl:	ld	a,(startop)
	or	a
	jp	nz,bskip
brun:	call	prep
	ld	hl,(cont)
	push	hl
	di
	ld	hl,(sbc)
	ld	b,h
	ld	c,l
	ld	hl,(saf)
	push	hl
	pop	af
	ld	de,bufd
	ld	hl,bufh
	ld	ix,bufx
	ld	iy,bufy
	ret
bskip:	ld	hl,(nexta)
	jp	(hl)

; fall-through exit: the whole sled was consumed
fall:	ld	(osp),sp
	ld	(ohl),hl
	ld	sp,capstk
	push	af
	ld	a,0
	jp	capture
; return exit: the sandbox return address was popped
rtrap:	ld	(osp),sp
	ld	(ohl),hl
	ld	sp,capstk
	push	af
	ld	a,1
	jp	capture
; RST 08h exit: the pushed address shows where execution resumed
rst8:	ld	(ohl),hl
	pop	hl
	ld	(oret),hl
	ld	(osp),sp
	ld	sp,capstk
	push	af
	ld	a,2
capture: ld	(oexit),a
	pop	hl		; AF
	ld	(oaf),hl
	ld	(obc),bc
	ld	(ode),de
	ld	(oix),ix
	ld	(oiy),iy
	ld	sp,(mainsp)
	ei
	jp	report

; prepare one probe: print "ED xx s ", select the set, fill the sandbox
prep:	ld	de,s_ed
	call	conmsg
	ld	a,(curop)
	call	conhex
	ld	e,' '
	ld	c,2
	call	bdosv
	ld	a,(curset)
	call	hexch
	ld	e,a
	ld	c,2
	call	bdosv
	ld	e,' '
	ld	c,2
	call	bdosv
	ld	a,(curset)
	add	a,a
	ld	e,a
	ld	d,0
	ld	hl,settab
	add	hl,de
	ld	e,(hl)
	inc	hl
	ld	d,(hl)
	ex	de,hl		; hl = set record
	ld	de,saf
	ld	bc,4
	ldir			; saf, sbc
	push	hl
	ld	hl,(sbc)
	ld	de,-4
	add	hl,de
	ex	de,hl
	pop	hl
	ld	bc,8
	ldir			; B window
	ld	de,bufd-4
	ld	bc,8
	ldir
	ld	de,bufh-4
	ld	bc,8
	ldir
	ld	de,bufx-4
	ld	bc,8
	ldir
	ld	de,bufy-4
	ld	bc,8
	ldir
	ld	de,tstk-4
	ld	bc,8
	ldir
	ld	hl,rtrap
	ld	(tstk),hl	; the sandbox return address
	ld	hl,obuf-4
	ld	(hl),0cfh
	ld	de,obuf-3
	ld	bc,7
	ldir			; O window: RST 08h bytes
	ld	a,0c3h
	ld	(8),a
	ld	hl,rst8
	ld	(9),hl
	ld	hl,0
	ld	(oret),hl
	ret

; write the result: "ED xx s " to the file only (the console has it), the
; rest to both; pad to {RECORD - 2} bytes, CR LF, close as a checkpoint; then run
; the next set or the next probe
report:	xor	a
	ld	(lcnt),a
	ld	a,'E'
	call	fonly
	ld	a,'D'
	call	fonly
	ld	a,' '
	call	fonly
	ld	a,(curop)
	call	fhex2
	ld	a,' '
	call	fonly
	ld	a,(curset)
	call	hexch
	call	fonly
	ld	a,' '
	call	fonly
	ld	de,s_fall
	ld	a,(oexit)
	or	a
	jp	z,rep1
	ld	de,s_ret
	dec	a
	jp	z,rep1
	ld	de,s_rst
rep1:	call	lputs
	ld	de,s_r
	call	lputs
	ld	hl,(oret)
	call	lhex4
	ld	de,s_l
	call	lputs
	ld	hl,(cont)
	ld	de,10		; first sled byte + 1
	add	hl,de
	ex	de,hl
	ld	hl,(oret)
	or	a
	sbc	hl,de
	call	lhex4
	ld	de,s_a
	call	lputs
	ld	a,(oaf+1)
	call	lhex2
	ld	de,s_f
	call	lputs
	ld	a,(oaf)
	call	lhex2
	ld	de,s_bc
	call	lputs
	ld	hl,(obc)
	call	lhex4
	ld	de,s_de
	call	lputs
	ld	hl,(ode)
	call	lhex4
	ld	de,s_hl
	call	lputs
	ld	hl,(ohl)
	call	lhex4
	ld	de,s_ix
	call	lputs
	ld	hl,(oix)
	call	lhex4
	ld	de,s_iy
	call	lputs
	ld	hl,(oiy)
	call	lhex4
	ld	de,s_sp
	call	lputs
	ld	hl,(osp)
	call	lhex4
	ld	de,s_b
	call	lputs
	ld	hl,(sbc)
	ld	de,-4
	add	hl,de
	call	lwin
	ld	de,s_d
	call	lputs
	ld	hl,bufd-4
	call	lwin
	ld	de,s_h
	call	lputs
	ld	hl,bufh-4
	call	lwin
	ld	de,s_x
	call	lputs
	ld	hl,bufx-4
	call	lwin
	ld	de,s_y
	call	lputs
	ld	hl,bufy-4
	call	lwin
	ld	de,s_s
	call	lputs
	ld	hl,tstk-4
	call	lwin
	ld	de,s_o
	call	lputs
	ld	hl,obuf-4
	call	lwin
	ld	e,13
	ld	c,2
	call	bdosv
	ld	e,10
	ld	c,2
	call	bdosv
rpad:	ld	a,(lcnt)
	cp	{RECORD - 2}
	jp	z,rend
	ld	a,' '
	call	fonly
	jp	rpad
rend:	ld	a,13
	call	fonly
	ld	a,10
	call	fonly		; completes the record
	ld	de,(curfcb)
	ld	c,16		; close as a checkpoint; writing continues
	call	bdosv
	ld	a,(curset)
	inc	a
	cp	{SETS}
	jp	z,rnext
	ld	(curset),a
	ld	hl,(cont)
	ld	de,-10		; the start of the probe body
	add	hl,de
	jp	(hl)
rnext:	xor	a
	ld	(curset),a
	ld	hl,(nexta)
	jp	(hl)

; file only, counted
fonly:	push	hl
	call	fputc
	ld	hl,lcnt
	inc	(hl)
	pop	hl
	ret

; console and file, counted
lput:	call	putc
	push	hl
	ld	hl,lcnt
	inc	(hl)
	pop	hl
	ret

lputs:	ld	a,(de)
	cp	'$'
	ret	z
	call	lput
	inc	de
	jp	lputs

; a as two hex digits: fhex2 to the file only, lhex2 to both
fhex2:	push	af
	rrca
	rrca
	rrca
	rrca
	call	hexch
	call	fonly
	pop	af
	call	hexch
	jp	fonly
lhex2:	push	af
	rrca
	rrca
	rrca
	rrca
	call	hexch
	call	lput
	pop	af
	call	hexch
	jp	lput
lhex4:	ld	a,h
	call	lhex2
	ld	a,l
	jp	lhex2
; the eight bytes at hl as hex
lwin:	ld	b,8
lwin1:	ld	a,(hl)
	call	lhex2
	inc	hl
	dec	b
	jp	nz,lwin1
	ret

; low nibble of a -> ASCII hex digit in a (table, no compare-and-adjust)
hexch:	push	de
	push	hl
	and	0fh
	ld	e,a
	ld	d,0
	ld	hl,hextab
	add	hl,de
	ld	a,(hl)
	pop	hl
	pop	de
	ret

; console only: a as two hex digits
conhex:	push	af
	rrca
	rrca
	rrca
	rrca
	call	hexch
	ld	e,a
	ld	c,2
	call	bdosv
	pop	af
	call	hexch
	ld	e,a
	ld	c,2
	call	bdosv
	ret

; parse the optional hex start opcode and '+' from the command tail, and
; name the output file {prefix}xx.TXT
parse:	xor	a
	ld	(startop),a
	ld	(allflg),a
	ld	hl,80h
	ld	b,(hl)		; tail length
	inc	hl
	inc	b
pskip:	dec	b
	jp	z,pplus
	ld	a,(hl)
	inc	hl
	cp	' '
	jp	z,pskip
	dec	hl
	inc	b
	ld	c,0		; value
	ld	d,2		; at most two digits
pdig:	dec	b
	jp	z,pdone
	ld	a,(hl)
	inc	hl
	cp	'0'
	jp	c,pdone
	cp	'9'+1
	jp	c,pnum
	cp	'A'
	jp	c,pdone
	cp	'F'+1
	jp	nc,pdone
	sub	'A'-10
	jp	pacc
pnum:	sub	'0'
pacc:	ld	e,a
	ld	a,c
	rlca
	rlca
	rlca
	rlca
	and	0f0h
	or	e
	ld	c,a
	dec	d
	jp	nz,pdig
pdone:	ld	a,c
	ld	(startop),a
pplus:	ld	hl,80h
	ld	b,(hl)
	inc	hl
	inc	b
pplus1:	dec	b
	jp	z,pname
	ld	a,(hl)
	inc	hl
	cp	'+'
	jp	nz,pplus1
	ld	a,1
	ld	(allflg),a
pname:	ld	a,(startop)
	push	af
	rrca
	rrca
	rrca
	rrca
	call	hexch
	ld	(fcbout+3),a
	pop	af
	call	hexch
	ld	(fcbout+4),a
	ret

title:	db	'{name} M102 undefined ED opcode probe 2',13,10,'$'
s_ed:	db	'ED $'
s_fall:	db	'FALL$'
s_ret:	db	'RET $'
s_rst:	db	'RST $'
s_r:	db	' R=$'
s_l:	db	' L=$'
s_a:	db	' A=$'
s_f:	db	' F=$'
s_bc:	db	' BC=$'
s_de:	db	' DE=$'
s_hl:	db	' HL=$'
s_ix:	db	' IX=$'
s_iy:	db	' IY=$'
s_sp:	db	' SP=$'
s_b:	db	' B=$'
s_d:	db	' D=$'
s_h:	db	' H=$'
s_x:	db	' X=$'
s_y:	db	' Y=$'
s_s:	db	' S=$'
s_o:	db	' O=$'
settab:	dw	{",".join(f"set{s}" for s in range(SETS))}
""")
    for s in range(SETS):
        lines.append(f"set{s}:\tdw\t0{SET_AF[s]:04x}h\t\t; AF\n\tdw\t0{SET_BC[s]:04x}h\t\t; BC\n")
        for index, _ in enumerate(BUFFERS):
            lines.append(db(pattern(s, index)))
    lines.append(f"""fcbout:	db	0,'{prefix}00    TXT'
	db	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
oldrst:	db	0,0,0
startop: db	0
allflg:	db	0
curop:	db	0
curset:	db	0
oexit:	db	0
lcnt:	db	0
saf:	dw	0
sbc:	dw	0
nexta:	dw	0
cont:	dw	0
mainsp:	dw	0
oret:	dw	0
osp:	dw	0
oaf:	dw	0
obc:	dw	0
ode:	dw	0
ohl:	dw	0
oix:	dw	0
oiy:	dw	0
codeend:
""")
    for label, value in ADDRESSES.items():
        lines.append(f"{label}:\tequ\t0{value:04x}h\n")
    return "".join(lines)


def record_count(name: str, include_exits: bool = True) -> int:
    variant = variants()[name]
    probes = [op for op in variant["probes"] if include_exits or op not in EXITS_EMULATION]
    return (len(variant["controls"]) + len(probes)) * SETS
