; Copyright (c) 2026 Nakata Maho
;
; Redistribution and use in source and binary forms, with or without
; modification, are permitted provided that the following conditions
; are met:
; 1. Redistributions of source code must retain the above copyright
;    notice, this list of conditions and the following disclaimer.
; 2. Redistributions in binary form must reproduce the above copyright
;    notice, this list of conditions and the following disclaimer in the
;    documentation and/or other materials provided with the distribution.
;
; THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
; IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
; OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
; IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
; INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
; BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
; USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
; ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
; (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
; THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;
; LOADER.BIN: menu and loader of the self-booting SGP demo disk (vaeg M106);
; see demos/sgp-boot/README.md. Assemble with NASM:
;   nasm -f bin -I build-dir/ -o LOADER.BIN loader.asm
; where build-dir/catalog.inc is generated by build-boot-d88.py.
;
; IPL.BIN loads this to 2000:0000. It lists the demos of catalog.inc, loads
; the chosen one from the disk as a .COM image at DEMO_SEG:0100 (a minimal
; PSP below it) and runs it with CS = DS = ES = SS = DEMO_SEG, SP = FFFEh.
; Without DOS, INT 21h and INT 20h are provided here: function 09h prints a
; '$'-terminated string through the ROM text BIOS (INT 83h), function 4Ch
; and INT 20h return to the menu, and other functions fail with CF = 1 and
; AX = 1. The demos use only 09h and 4Ch with the ROM BIOS and the hardware.
		cpu	186
		org	0
LOADER_SEG	equ	2000h
DEMO_SEG	equ	4000h
SECTORS		equ	9		; per track
RETRIES		equ	4

start:		cli
		mov	ax,cs
		mov	ds,ax
		mov	ss,ax
		mov	sp,0fffeh
		xor	ax,ax			; INT 20h and 21h vectors
		mov	es,ax
		mov	word [es:20h * 4],int20
		mov	[es:20h * 4 + 2],cs
		mov	word [es:21h * 4],int21
		mov	[es:21h * 4 + 2],cs
		sti
		cld

menu:		mov	ax,cs
		mov	ds,ax
		mov	es,ax
		mov	ah,2ah			; text BIOS: initialise the text screen
		int	83h
		mov	ax,1702h		; clear the whole split screen
		int	83h
		xor	dx,dx			; cursor to the top left
		mov	ah,08h
		int	83h
		mov	si,title
		call	puts
		mov	si,catalog
		mov	bl,'A'
.item:		cmp	word [si],0
		je	.prompt
		mov	al,' '
		call	putc
		mov	al,bl
		call	putc
		mov	al,' '
		call	putc
		call	putc
		push	si
		mov	si,[si + 4]		; label
		call	puts
		mov	si,crlf
		call	puts
		pop	si
		add	si,6			; dw first sector, dw sectors, dw label
		inc	bl
		jmp	.item
.prompt:	mov	si,prompt
		call	puts
.key:		call	wait_key
		and	al,0dfh			; upper case
		sub	al,'A'
		jb	.key
		xor	ah,ah
		cmp	ax,[catalog_count]
		jae	.key
		mov	bx,ax
		shl	bx,1
		add	bx,ax
		shl	bx,1			; 6 bytes an entry
		lea	si,[catalog + bx]
		call	load
		jc	.failed
		jmp	run
.failed:	mov	si,read_error
		call	puts
		call	wait_key
		jmp	menu

; load the catalog entry at SI (dw first logical sector, dw sectors) to
; DEMO_SEG:0100; CF = 1 on a read error
load:		mov	ax,DEMO_SEG		; PSP: INT 20h at 0, empty command tail
		mov	es,ax
		xor	di,di
		mov	cx,80h
		xor	ax,ax
		rep	stosw
		mov	word [es:0000h],20cdh
		mov	word [es:0002h],0a000h
		mov	word [es:0080h],0d00h
		mov	ax,[si]			; first logical sector
		mov	di,[si + 2]		; sectors
		mov	si,ax
		mov	bp,0100h
.next:		or	di,di
		jz	.done
		mov	ax,si
		mov	bl,SECTORS
		div	bl
		mov	cl,al			; track
		mov	dh,ah
		inc	dh			; sector
		mov	al,SECTORS + 1
		sub	al,dh
		xor	ah,ah
		cmp	ax,di
		jbe	.count
		mov	ax,di
.count:		mov	[cs:count],al
		mov	byte [cs:tries],RETRIES
.read:		mov	al,[cs:count]
		mov	ah,01h			; read, with retry
		xor	bx,bx			; BH/BL: ID cylinder/head if BIOSMODE asks
		xor	ch,ch			; drive 1
		mov	dl,02h			; MFM, 512 bytes
		int	80h
		jnc	.ok
		dec	byte [cs:tries]
		jz	.error
		mov	ah,06h			; recalibrate, then try again
		xor	ch,ch
		int	80h
		jmp	.read
.ok:		mov	bl,[cs:count]
		xor	bh,bh
		add	si,bx
		sub	di,bx
		shl	bx,9
		add	bp,bx
		jmp	.next
.done:		clc
		ret
.error:		stc
		ret

; start the loaded program as DOS would start a .COM file
run:		cli
		mov	ax,DEMO_SEG
		mov	ds,ax
		mov	es,ax
		mov	ss,ax
		mov	sp,0fffeh
		push	word 0			; RET reaches INT 20h at PSP:0000
		sti
		xor	ax,ax
		xor	bx,bx
		mov	cx,00ffh
		xor	dx,dx
		xor	si,si
		xor	di,di
		xor	bp,bp
		jmp	DEMO_SEG:0100h

; the program ended (INT 20h, or INT 21h function 4Ch)
finished:	cli
		mov	ax,cs
		mov	ds,ax
		mov	ss,ax
		mov	sp,0fffeh
		sti
		cld
		mov	si,ended
		call	puts
		call	wait_key
		jmp	menu

int20:		jmp	finished

int21:		cmp	ah,4ch
		je	finished
		cmp	ah,09h
		je	.print
		mov	ax,1			; not provided: CF = 1, AX = 1
		push	bp
		mov	bp,sp
		or	byte [bp + 6],01h
		pop	bp
		iret
.print:		push	ax			; DS:DX: string ended by '$'
		push	dx
		push	si
		mov	si,dx
.p:		lodsb
		cmp	al,'$'
		je	.pd
		call	putc
		jmp	.p
.pd:		pop	si
		pop	dx
		pop	ax
		mov	al,'$'
		iret

; one character AL through the text BIOS (control codes act)
putc:		push	ax
		push	dx
		xor	ah,ah
		mov	dx,ax
		int	83h
		pop	dx
		pop	ax
		ret

; the zero-terminated string at CS:SI
puts:		push	ax
.l:		mov	al,[cs:si]
		inc	si
		or	al,al
		jz	.r
		call	putc
		jmp	.l
.r:		pop	ax
		ret

; drop pending keys, then wait for one: AH = scan code, AL = internal code.
; Functions 09h/0Ch are the keyboard BIOS's basic functions; function 00h
; would wait on the Japanese front end, which only an OS installs.
wait_key:	mov	ah,0ch
		int	82h
		mov	ah,09h
		int	82h
		ret

title		db	'PC-88VA SGP demos (self-booting disk, vaeg M106)', 13, 10, 13, 10, 0
prompt		db	13, 10, 'Press a letter to run a demo. ESC in a demo returns here.', 13, 10, 0
read_error	db	13, 10, 'Disk read error. Press a key.', 13, 10, 0
ended		db	13, 10, 'Demo ended. Press a key for the menu.', 13, 10, 0
crlf		db	13, 10, 0
count		db	0
tries		db	0

%include "catalog.inc"
