#!/usr/bin/env python3
# Copyright (c) 2026 Nakata Maho
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""Generate the deterministic M98s 64-phase fixed-point orbit include."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

PHASE_COUNT = 64
FIXED_ONE = 65536
# Canonical Q16 values for sin(k*pi/32), k=0..16.  The endpoints are exact;
# the interior values are the frozen nearest integers.  Generation therefore
# has no dependency on host floating-point or libm behavior.
QUARTER_SINE_Q16 = (
    0, 6424, 12785, 19024, 25080, 30893, 36410, 41576, 46341,
    50660, 54491, 57798, 60547, 62714, 64277, 65220, 65536,
)


def round_half_away(numerator: int, denominator: int = FIXED_ONE) -> int:
    if numerator < 0:
        return -((-numerator + denominator // 2) // denominator)
    return (numerator + denominator // 2) // denominator


def unit_entry(phase: int) -> tuple[int, int]:
    if not 0 <= phase < PHASE_COUNT:
        raise ValueError("M98S_PHASE_RANGE")
    quadrant, step = divmod(phase, 16)
    if quadrant == 0:
        return QUARTER_SINE_Q16[16 - step], QUARTER_SINE_Q16[step]
    if quadrant == 1:
        return -QUARTER_SINE_Q16[step], QUARTER_SINE_Q16[16 - step]
    if quadrant == 2:
        return -QUARTER_SINE_Q16[16 - step], -QUARTER_SINE_Q16[step]
    return QUARTER_SINE_Q16[step], -QUARTER_SINE_Q16[16 - step]


def generate(radius_x: int, radius_y: int) -> tuple[tuple[int, int], ...]:
    if not 0 < radius_x <= 32767 or not 0 < radius_y <= 32767:
        raise ValueError("M98S_RADIUS_RANGE")
    return tuple((round_half_away(x * radius_x),
                  round_half_away(y * radius_y))
                 for x, y in map(unit_entry, range(PHASE_COUNT)))


def encode_include(entries: tuple[tuple[int, int], ...], radius_x: int,
                   radius_y: int) -> bytes:
    lines = [
        "; Copyright (c) 2026 Nakata Maho",
        ";",
        "; Redistribution and use in source and binary forms, with or without",
        "; modification, are permitted provided that the following conditions are met:",
        "; 1. Redistributions of source code must retain the above copyright notice,",
        ";    this list of conditions and the following disclaimer.",
        "; 2. Redistributions in binary form must reproduce the above copyright notice,",
        ";    this list of conditions and the following disclaimer in the documentation",
        ";    and/or other materials provided with the distribution.",
        ";",
        "; THIS SOFTWARE IS PROVIDED BY THE AUTHOR \"AS IS\" AND ANY EXPRESS OR IMPLIED",
        "; WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF",
        "; MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO",
        "; EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,",
        "; SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,",
        "; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;",
        "; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,",
        "; WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR",
        "; OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF",
        "; ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
        ";",
        "; Generated by generate_zundamon_orbit_table.py.  Do not edit by hand.",
        f"%define ORBIT_TABLE_PHASE_COUNT {len(entries)}",
        f"%define ORBIT_TABLE_RADIUS_X {radius_x}",
        f"%define ORBIT_TABLE_RADIUS_Y {radius_y}",
        "orbit_offsets:",
    ]
    lines.extend(f"    dw {dx:4d}, {dy:4d} ; phase {phase:02d}"
                 for phase, (dx, dy) in enumerate(entries))
    return ("\n".join(lines) + "\n").encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--radius-x", type=int, default=96)
    parser.add_argument("--radius-y", type=int, default=48)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--metadata", type=Path)
    args = parser.parse_args()
    if args.output.exists() or (args.metadata is not None and args.metadata.exists()):
        parser.error("refusing to overwrite generated output")
    entries = generate(args.radius_x, args.radius_y)
    encoded = encode_include(entries, args.radius_x, args.radius_y)
    args.output.write_bytes(encoded)
    digest = hashlib.sha256(encoded).hexdigest()
    if args.metadata is not None:
        args.metadata.write_text(json.dumps({
            "schema": "zundamon-orbit-m98s-table-v1",
            "phase_count": PHASE_COUNT,
            "radius_x": args.radius_x,
            "radius_y": args.radius_y,
            "sha256": digest,
            "entries": [{"phase": phase, "dx": dx, "dy": dy}
                        for phase, (dx, dy) in enumerate(entries)],
        }, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"M98S_ORBIT_GENERATION_PASS phases={PHASE_COUNT} "
          f"radius_x={args.radius_x} radius_y={args.radius_y} sha256={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
