# Copyright (c) 2026 Nakata Maho
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# Embed notices at configure time; the running application needs no license files.
set(VAEG_LICENSE_HEADER "${CMAKE_CURRENT_BINARY_DIR}/generated/vaeg_licenses.h")
file(WRITE "${VAEG_LICENSE_HEADER}"
    "// Generated by cmake/third_party_licenses.cmake.\n"
    "struct VaegLicense { const char *name; const char *text; };\n"
    "static const VaegLicense vaeg_licenses[] = {\n")

function(vaeg_license name path)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    file(READ "${path}" notice)
    if(ARGC GREATER 2)
        if(ARGV2 STREQUAL "header")
            string(FIND "${notice}" "/*" start)
            string(FIND "${notice}" "*/" end)
            if(start LESS 0 OR end LESS start)
                message(FATAL_ERROR "Missing license header: ${path}")
            endif()
            math(EXPR start "${start} + 2")
            math(EXPR length "${end} - ${start}")
            string(SUBSTRING "${notice}" ${start} ${length} notice)
        elseif(ARGV2 STREQUAL "stb")
            string(FIND "${notice}" "ALTERNATIVE A - MIT License" start)
            if(start LESS 0)
                message(FATAL_ERROR "Missing stb license: ${path}")
            endif()
            string(SUBSTRING "${notice}" ${start} -1 notice)
            string(FIND "${notice}" "*/" end)
            string(SUBSTRING "${notice}" 0 ${end} notice)
        endif()
    endif()
    if(notice MATCHES "\\)vaeglicense\"")
        message(FATAL_ERROR "License raw-string delimiter collision: ${path}")
    endif()
    file(APPEND "${VAEG_LICENSE_HEADER}"
        "{\"${name}\", R\"vaeglicense(${notice})vaeglicense\"},\n")
endfunction()

vaeg_license("VAEG / Neko Project II - legacy notice"
    "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES/legacy-vaeg.txt")
vaeg_license("Bundled assets - font, startup graphic, icon, provenance"
    "${CMAKE_CURRENT_SOURCE_DIR}/assets/NOTICE.md")
vaeg_license("SDL2 - zlib license"
    "${CMAKE_CURRENT_SOURCE_DIR}/docs/licenses/sdl2-notice.txt")
if(VAEG_FETCH_SDL2)
    vaeg_license("SDL2 - license from this build"
        "${sdl2_SOURCE_DIR}/LICENSE.txt")
    vaeg_license("SDL2 / HIDAPI - original BSD-style license"
        "${sdl2_SOURCE_DIR}/src/hidapi/LICENSE-orig.txt")
    vaeg_license("SDL2 / yuv2rgb - BSD"
        "${sdl2_SOURCE_DIR}/src/video/yuv2rgb/LICENSE")
endif()
vaeg_license("Dear ImGui - MIT"
    "${CMAKE_CURRENT_SOURCE_DIR}/external/imgui/LICENSE.txt")
foreach(component rectpack textedit truetype)
    vaeg_license("stb_${component} (Dear ImGui) - MIT / public domain"
        "${CMAKE_CURRENT_SOURCE_DIR}/external/imgui/imstb_${component}.h" stb)
endforeach()
vaeg_license("ymfm - BSD-3-Clause"
    "${CMAKE_CURRENT_SOURCE_DIR}/external/ymfm/LICENSE")
vaeg_license("ymfm - source revision and integration"
    "${CMAKE_CURRENT_SOURCE_DIR}/docs/agents/DECISIONS/ADR-0009-opn-backend.md")
vaeg_license("suzukiplan Z80 - MIT"
    "${CMAKE_CURRENT_SOURCE_DIR}/external/suzukiplan-z80/LICENSE.txt")
vaeg_license("suzukiplan Z80 - source revision"
    "${CMAKE_CURRENT_SOURCE_DIR}/external/suzukiplan-z80/provenance.txt")
vaeg_license("Noto Sans JP - SIL Open Font License 1.1"
    "${CMAKE_CURRENT_SOURCE_DIR}/assets/OFL.txt")
if(VAEG_ENABLE_ARCHIVE_DROP AND (MINGW OR VAEG_FETCH_LIBARCHIVE OR LibArchive_FOUND))
    vaeg_license("LibArchive - license and source reference"
        "${CMAKE_CURRENT_SOURCE_DIR}/docs/licenses/libarchive-notice.txt")
    if(MINGW OR VAEG_FETCH_LIBARCHIVE)
        vaeg_license("zlib - pinned source reference"
            "${CMAKE_CURRENT_SOURCE_DIR}/docs/licenses/zlib-notice.txt")
        vaeg_license("liblzma - pinned source reference"
            "${CMAKE_CURRENT_SOURCE_DIR}/docs/licenses/liblzma-notice.txt")
        vaeg_license("zlib 1.3.1 - zlib license"
            "${vaeg_zlib_SOURCE_DIR}/LICENSE")
        vaeg_license("liblzma 5.8.3 - licensing overview"
            "${vaeg_xz_SOURCE_DIR}/COPYING")
        vaeg_license("liblzma 5.8.3 - 0BSD"
            "${vaeg_xz_SOURCE_DIR}/COPYING.0BSD")
        vaeg_license("LibArchive 3.8.7 - compress reader notice"
            "${vaeg_libarchive_SOURCE_DIR}/libarchive/archive_read_support_filter_compress.c" header)
        vaeg_license("LibArchive 3.8.7 - compress writer notice"
            "${vaeg_libarchive_SOURCE_DIR}/libarchive/archive_write_add_filter_compress.c" header)
    endif()
endif()
if(VAEG_ENABLE_LIBRASHADER)
    if(VAEG_STATIC_LIBRASHADER)
        vaeg_license("librashader static dependency notices and sources"
            "${VAEG_LIBRASHADER_STATIC_NOTICES}")
    endif()
    vaeg_license("librashader v0.12.0 - MPL-2.0"
        "${CMAKE_CURRENT_SOURCE_DIR}/external/librashader/LICENSE.md")
    vaeg_license("librashader C API / loader - MIT"
        "${CMAKE_CURRENT_SOURCE_DIR}/external/librashader/include/librashader_ld.h" header)
    vaeg_license("librashader - source, versions and provenance"
        "${CMAKE_CURRENT_SOURCE_DIR}/docs/agents/DECISIONS/ADR-0014-librashader-crt.md")
    vaeg_license("CRT Lottes - Unlicense"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/shaders/crt/licenses/crt-default-license.txt")
    vaeg_license("VAEG CRT - BSD-2-Clause"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/shaders/crt/shaders/vaeg-crt-aa.slang" header)
    vaeg_license("CRT shaders - sources and provenance"
        "${CMAKE_CURRENT_SOURCE_DIR}/assets/shaders/crt/licenses/crt-default-provenance.md")
endif()
file(APPEND "${VAEG_LICENSE_HEADER}" "};\n")
